module.exports = {
    apps: [
        {
            name: 'server',
            cwd: '/home/justfrenzy/share/graduate_work/server',
            script: 'npm',
            args: 'start',
            log_file: '/home/justfrenzy/share/graduate_work/logs/backend.log',
            error_file: '/home/justfrenzy/share/graduate_work/logs/backend_error.log',
            time: true,
            watch: true,
        },
        {
            name: 'client',
            cwd: '/home/justfrenzy/share/graduate_work/client',
            script: 'npm',
            args: 'start',
            log_file: '/home/justfrenzy/share/graduate_work/logs/frontend.log',
            error_file: '/home/justfrenzy/share/graduate_work/logs/frontend_error.log',
            time: true,
            watch: true,
        },
        {
            name: 'frontend_dev',
            cwd: '/home/justfrenzy/share/graduate_work/client',
            script: 'npm',
            args: 'run dev',
            log_file: '/home/justfrenzy/share/graduate_work/logs/frontend_dev.log',
            error_file: '/home/justfrenzy/share/graduate_work/logs/frontend_dev_error.log',
            time: true,
            watch: true,
        },
        {
            name: 'frontend',
            cwd: '/home/justfrenzy/share/bet-room/bet-room-1/frontend',
            script: 'npm',
            args: 'run dev',
            log_file: '/home/justfrenzy/share/bet-room/bet-room-1/logs/frontend.log',
            error_file: '/home/justfrenzy/share/bet-room/bet-room-1/logs/frontend_error.log',
            time: true,
            watch: true,
        },
        {
            name: 'backend',
            cwd: '/home/justfrenzy/share/bet-room/bet-room-1/back-end',
            script: 'npm',
            args: 'start',
            log_file: '/home/justfrenzy/share/bet-room/bet-room-1/logs/backend.log',
            error_file: '/home/justfrenzy/share/bet-room/bet-room-1/logs/backend_error.log',
            time: true,
            watch: true,
        },
    ],
};