export const countryInit = [
	{
		iso_3166_1: "AD",
		english_name: "Andorra",
		native_name: "Андора",
		is: false,
	},
	{
		iso_3166_1: "AE",
		english_name: "United Arab Emirates",
		native_name: "Обединени арабски емирства",
		is: false,
	},
	{
		iso_3166_1: "AF",
		english_name: "Afghanistan",
		native_name: "Афганистан",
		is: false,
	},
	{
		iso_3166_1: "AG",
		english_name: "Antigua and Barbuda",
		native_name: "Антигуа и Барбуда",
		is: false,
	},
	{
		iso_3166_1: "AI",
		english_name: "Anguilla",
		native_name: "Ангуила",
		is: false,
	},
	{
		iso_3166_1: "AL",
		english_name: "Albania",
		native_name: "Албания",
		is: false,
	},
	{
		iso_3166_1: "AM",
		english_name: "Armenia",
		native_name: "Армения",
		is: false,
	},
	{
		iso_3166_1: "AN",
		english_name: "Netherlands Antilles",
		native_name: "Холандски Антили",
		is: false,
	},
	{
		iso_3166_1: "AO",
		english_name: "Angola",
		native_name: "Ангола",
		is: false,
	},
	{
		iso_3166_1: "AQ",
		english_name: "Antarctica",
		native_name: "Антарктика",
		is: false,
	},
	{
		iso_3166_1: "AR",
		english_name: "Argentina",
		native_name: "Аржентина",
		is: false,
	},
	{
		iso_3166_1: "AS",
		english_name: "American Samoa",
		native_name: "Американска Самоа",
		is: false,
	},
	{
		iso_3166_1: "AT",
		english_name: "Austria",
		native_name: "Австрия",
		is: false,
	},
	{
		iso_3166_1: "AU",
		english_name: "Australia",
		native_name: "Австралия",
		is: false,
	},
	{
		iso_3166_1: "AW",
		english_name: "Aruba",
		native_name: "Аруба",
		is: false,
	},
	{
		iso_3166_1: "AZ",
		english_name: "Azerbaijan",
		native_name: "Азербайджан",
		is: false,
	},
	{
		iso_3166_1: "BA",
		english_name: "Bosnia and Herzegovina",
		native_name: "Босна и Херцеговина",
		is: false,
	},
	{
		iso_3166_1: "BB",
		english_name: "Barbados",
		native_name: "Барбадос",
		is: false,
	},
	{
		iso_3166_1: "BD",
		english_name: "Bangladesh",
		native_name: "Бангладеш",
		is: false,
	},
	{
		iso_3166_1: "BE",
		english_name: "Belgium",
		native_name: "Белгия",
		is: false,
	},
	{
		iso_3166_1: "BF",
		english_name: "Burkina Faso",
		native_name: "Буркина Фасо",
		is: false,
	},
	{
		iso_3166_1: "BG",
		english_name: "Bulgaria",
		native_name: "България",
		is: false,
	},
	{
		iso_3166_1: "BH",
		english_name: "Bahrain",
		native_name: "Бахрейн",
		is: false,
	},
	{
		iso_3166_1: "BI",
		english_name: "Burundi",
		native_name: "Бурунди",
		is: false,
	},
	{
		iso_3166_1: "BJ",
		english_name: "Benin",
		native_name: "Бенин",
		is: false,
	},
	{
		iso_3166_1: "BM",
		english_name: "Bermuda",
		native_name: "Бермуда",
		is: false,
	},
	{
		iso_3166_1: "BN",
		english_name: "Brunei Darussalam",
		native_name: "Бруней Дарусалам",
		is: false,
	},
	{
		iso_3166_1: "BO",
		english_name: "Bolivia",
		native_name: "Боливия",
		is: false,
	},
	{
		iso_3166_1: "BR",
		english_name: "Brazil",
		native_name: "Бразилия",
		is: false,
	},
	{
		iso_3166_1: "BS",
		english_name: "Bahamas",
		native_name: "Бахами",
		is: false,
	},
	{
		iso_3166_1: "BT",
		english_name: "Bhutan",
		native_name: "Бутан",
		is: false,
	},
	{
		iso_3166_1: "BU",
		english_name: "Burma",
		native_name: "Burma",
		is: false,
	},
	{
		iso_3166_1: "BV",
		english_name: "Bouvet Island",
		native_name: "остров Буве",
		is: false,
	},
	{
		iso_3166_1: "BW",
		english_name: "Botswana",
		native_name: "Ботсвана",
		is: false,
	},
	{
		iso_3166_1: "BY",
		english_name: "Belarus",
		native_name: "Беларус",
		is: false,
	},
	{
		iso_3166_1: "BZ",
		english_name: "Belize",
		native_name: "Белиз",
		is: false,
	},
	{
		iso_3166_1: "CA",
		english_name: "Canada",
		native_name: "Канада",
		is: false,
	},
	{
		iso_3166_1: "CC",
		english_name: "Cocos  Islands",
		native_name: "Кокосови острови (острови Кийлинг)",
		is: false,
	},
	{
		iso_3166_1: "CD",
		english_name: "Congo",
		native_name: "Демократична република Конго",
		is: false,
	},
	{
		iso_3166_1: "CF",
		english_name: "Central African Republic",
		native_name: "Централноафриканска република",
		is: false,
	},
	{
		iso_3166_1: "CH",
		english_name: "Switzerland",
		native_name: "Швейцария",
		is: false,
	},
	{
		iso_3166_1: "CI",
		english_name: "Cote D'Ivoire",
		native_name: "Кот д’Ивоар",
		is: false,
	},
	{
		iso_3166_1: "CK",
		english_name: "Cook Islands",
		native_name: "острови Кук",
		is: false,
	},
	{
		iso_3166_1: "CL",
		english_name: "Chile",
		native_name: "Чили",
		is: false,
	},
	{
		iso_3166_1: "CM",
		english_name: "Cameroon",
		native_name: "Камерун",
		is: false,
	},
	{
		iso_3166_1: "CN",
		english_name: "China",
		native_name: "Китай",
		is: false,
	},
	{
		iso_3166_1: "CO",
		english_name: "Colombia",
		native_name: "Колумбия",
		is: false,
	},
	{
		iso_3166_1: "CR",
		english_name: "Costa Rica",
		native_name: "Коста Рика",
		is: false,
	},
	{
		iso_3166_1: "CS",
		english_name: "Serbia and Montenegro",
		native_name: "Serbia and Montenegro",
		is: false,
	},
	{
		iso_3166_1: "CU",
		english_name: "Cuba",
		native_name: "Куба",
		is: false,
	},
	{
		iso_3166_1: "CV",
		english_name: "Cape Verde",
		native_name: "Кабо Верде",
		is: false,
	},
	{
		iso_3166_1: "CX",
		english_name: "Christmas Island",
		native_name: "остров Рождество",
		is: false,
	},
	{
		iso_3166_1: "CY",
		english_name: "Cyprus",
		native_name: "Кипър",
		is: false,
	},
	{
		iso_3166_1: "CZ",
		english_name: "Czech Republic",
		native_name: "Чехия",
		is: false,
	},
	{
		iso_3166_1: "DE",
		english_name: "Germany",
		native_name: "Германия",
		is: false,
	},
	{
		iso_3166_1: "DJ",
		english_name: "Djibouti",
		native_name: "Джибути",
		is: false,
	},
	{
		iso_3166_1: "DK",
		english_name: "Denmark",
		native_name: "Дания",
		is: false,
	},
	{
		iso_3166_1: "DM",
		english_name: "Dominica",
		native_name: "Доминика",
		is: false,
	},
	{
		iso_3166_1: "DO",
		english_name: "Dominican Republic",
		native_name: "Доминиканска република",
		is: false,
	},
	{
		iso_3166_1: "DZ",
		english_name: "Algeria",
		native_name: "Алжир",
		is: false,
	},
	{
		iso_3166_1: "EC",
		english_name: "Ecuador",
		native_name: "Еквадор",
		is: false,
	},
	{
		iso_3166_1: "EE",
		english_name: "Estonia",
		native_name: "Естония",
		is: false,
	},
	{
		iso_3166_1: "EG",
		english_name: "Egypt",
		native_name: "Египет",
		is: false,
	},
	{
		iso_3166_1: "EH",
		english_name: "Western Sahara",
		native_name: "Западна Сахара",
		is: false,
	},
	{
		iso_3166_1: "ER",
		english_name: "Eritrea",
		native_name: "Еритрея",
		is: false,
	},
	{
		iso_3166_1: "ES",
		english_name: "Spain",
		native_name: "Испания",
		is: false,
	},
	{
		iso_3166_1: "ET",
		english_name: "Ethiopia",
		native_name: "Етиопия",
		is: false,
	},
	{
		iso_3166_1: "FI",
		english_name: "Finland",
		native_name: "Финландия",
		is: false,
	},
	{
		iso_3166_1: "FJ",
		english_name: "Fiji",
		native_name: "Фиджи",
		is: false,
	},
	{
		iso_3166_1: "FK",
		english_name: "Falkland Islands",
		native_name: "Фолклендски острови",
		is: false,
	},
	{
		iso_3166_1: "FM",
		english_name: "Micronesia",
		native_name: "Микронезия",
		is: false,
	},
	{
		iso_3166_1: "FO",
		english_name: "Faeroe Islands",
		native_name: "Фарьорски острови",
		is: false,
	},
	{
		iso_3166_1: "FR",
		english_name: "France",
		native_name: "Франция",
		is: false,
	},
	{
		iso_3166_1: "GA",
		english_name: "Gabon",
		native_name: "Габон",
		is: false,
	},
	{
		iso_3166_1: "GB",
		english_name: "United Kingdom",
		native_name: "Великобритания",
		is: false,
	},
	{
		iso_3166_1: "GD",
		english_name: "Grenada",
		native_name: "Гренада",
		is: false,
	},
	{
		iso_3166_1: "GE",
		english_name: "Georgia",
		native_name: "Грузия",
		is: false,
	},
	{
		iso_3166_1: "GF",
		english_name: "French Guiana",
		native_name: "Френска Гвиана",
		is: false,
	},
	{
		iso_3166_1: "GH",
		english_name: "Ghana",
		native_name: "Гана",
		is: false,
	},
	{
		iso_3166_1: "GI",
		english_name: "Gibraltar",
		native_name: "Гибралтар",
		is: false,
	},
	{
		iso_3166_1: "GL",
		english_name: "Greenland",
		native_name: "Гренландия",
		is: false,
	},
	{
		iso_3166_1: "GM",
		english_name: "Gambia",
		native_name: "Гамбия",
		is: false,
	},
	{
		iso_3166_1: "GN",
		english_name: "Guinea",
		native_name: "Гвинея",
		is: false,
	},
	{
		iso_3166_1: "GP",
		english_name: "Guadaloupe",
		native_name: "Гваделупа",
		is: false,
	},
	{
		iso_3166_1: "GQ",
		english_name: "Equatorial Guinea",
		native_name: "Екваториална Гвинея",
		is: false,
	},
	{
		iso_3166_1: "GR",
		english_name: "Greece",
		native_name: "Гърция",
		is: false,
	},
	{
		iso_3166_1: "GS",
		english_name: "South Georgia and the South Sandwich Islands",
		native_name: "Южна Джорджия и Южни Сандвичеви острови",
		is: false,
	},
	{
		iso_3166_1: "GT",
		english_name: "Guatemala",
		native_name: "Гватемала",
		is: false,
	},
	{
		iso_3166_1: "GU",
		english_name: "Guam",
		native_name: "Гуам",
		is: false,
	},
	{
		iso_3166_1: "GW",
		english_name: "Guinea-Bissau",
		native_name: "Гвинея-Бисау",
		is: false,
	},
	{
		iso_3166_1: "GY",
		english_name: "Guyana",
		native_name: "Гаяна",
		is: false,
	},
	{
		iso_3166_1: "HK",
		english_name: "Hong Kong",
		native_name: "Хонконг, САР на Китай",
		is: false,
	},
	{
		iso_3166_1: "HM",
		english_name: "Heard and McDonald Islands",
		native_name: "остров Хърд и острови Макдоналд",
		is: false,
	},
	{
		iso_3166_1: "HN",
		english_name: "Honduras",
		native_name: "Хондурас",
		is: false,
	},
	{
		iso_3166_1: "HR",
		english_name: "Croatia",
		native_name: "Хърватия",
		is: false,
	},
	{
		iso_3166_1: "HT",
		english_name: "Haiti",
		native_name: "Хаити",
		is: false,
	},
	{
		iso_3166_1: "HU",
		english_name: "Hungary",
		native_name: "Унгария",
		is: false,
	},
	{
		iso_3166_1: "ID",
		english_name: "Indonesia",
		native_name: "Индонезия",
		is: false,
	},
	{
		iso_3166_1: "IE",
		english_name: "Ireland",
		native_name: "Ирландия",
		is: false,
	},
	{
		iso_3166_1: "IL",
		english_name: "Israel",
		native_name: "Израел",
		is: false,
	},
	{
		iso_3166_1: "IN",
		english_name: "India",
		native_name: "Индия",
		is: false,
	},
	{
		iso_3166_1: "IO",
		english_name: "British Indian Ocean Territory",
		native_name: "Британска територия в Индийския океан",
		is: false,
	},
	{
		iso_3166_1: "IQ",
		english_name: "Iraq",
		native_name: "Ирак",
		is: false,
	},
	{
		iso_3166_1: "IR",
		english_name: "Iran",
		native_name: "Иран",
		is: false,
	},
	{
		iso_3166_1: "IS",
		english_name: "Iceland",
		native_name: "Исландия",
		is: false,
	},
	{
		iso_3166_1: "IT",
		english_name: "Italy",
		native_name: "Италия",
		is: false,
	},
	{
		iso_3166_1: "JM",
		english_name: "Jamaica",
		native_name: "Ямайка",
		is: false,
	},
	{
		iso_3166_1: "JO",
		english_name: "Jordan",
		native_name: "Йордания",
		is: false,
	},
	{
		iso_3166_1: "JP",
		english_name: "Japan",
		is: false,
		native_name: "Япония",
	},
	{
		iso_3166_1: "KE",
		english_name: "Kenya",
		native_name: "Кения",
		is: false,
	},
	{
		iso_3166_1: "KG",
		english_name: "Kyrgyz Republic",
		native_name: "Киргизстан",
		is: false,
	},
	{
		iso_3166_1: "KH",
		english_name: "Cambodia",
		native_name: "Камбоджа",
		is: false,
	},
	{
		iso_3166_1: "KI",
		english_name: "Kiribati",
		native_name: "Кирибати",
		is: false,
	},
	{
		iso_3166_1: "KM",
		english_name: "Comoros",
		native_name: "Коморски острови",
		is: false,
	},
	{
		iso_3166_1: "KN",
		english_name: "St. Kitts and Nevis",
		native_name: "Сейнт Китс и Невис",
		is: false,
	},
	{
		iso_3166_1: "KP",
		english_name: "North Korea",
		native_name: "Северна Корея",
		is: false,
	},
	{
		iso_3166_1: "KR",
		english_name: "South Korea",
		native_name: "Южна Корея",
		is: false,
	},
	{
		iso_3166_1: "KW",
		english_name: "Kuwait",
		native_name: "Кувейт",
		is: false,
	},
	{
		iso_3166_1: "KY",
		english_name: "Cayman Islands",
		native_name: "Кайманови острови",
		is: false,
	},
	{
		iso_3166_1: "KZ",
		english_name: "Kazakhstan",
		native_name: "Казахстан",
		is: false,
	},
	{
		iso_3166_1: "LA",
		english_name: "Lao People's Democratic Republic",
		native_name: "Лаос",
		is: false,
	},
	{
		iso_3166_1: "LB",
		english_name: "Lebanon",
		native_name: "Ливан",
		is: false,
	},
	{
		iso_3166_1: "LC",
		english_name: "St. Lucia",
		native_name: "Сейнт Лусия",
		is: false,
	},
	{
		iso_3166_1: "LI",
		english_name: "Liechtenstein",
		native_name: "Лихтенщайн",
		is: false,
	},
	{
		iso_3166_1: "LK",
		english_name: "Sri Lanka",
		native_name: "Шри Ланка",
		is: false,
	},
	{
		iso_3166_1: "LR",
		english_name: "Liberia",
		native_name: "Либерия",
		is: false,
	},
	{
		iso_3166_1: "LS",
		english_name: "Lesotho",
		native_name: "Лесото",
		is: false,
	},
	{
		iso_3166_1: "LT",
		english_name: "Lithuania",
		native_name: "Литва",
		is: false,
	},
	{
		iso_3166_1: "LU",
		english_name: "Luxembourg",
		native_name: "Люксембург",
		is: false,
	},
	{
		iso_3166_1: "LV",
		english_name: "Latvia",
		native_name: "Латвия",
		is: false,
	},
	{
		iso_3166_1: "LY",
		english_name: "Libyan Arab Jamahiriya",
		native_name: "Либия",
		is: false,
	},
	{
		iso_3166_1: "MA",
		english_name: "Morocco",
		native_name: "Мароко",
		is: false,
	},
	{
		iso_3166_1: "MC",
		english_name: "Monaco",
		native_name: "Монако",
		is: false,
	},
	{
		iso_3166_1: "MD",
		english_name: "Moldova",
		native_name: "Молдова",
		is: false,
	},
	{
		iso_3166_1: "ME",
		english_name: "Montenegro",
		native_name: "Черна гора",
		is: false,
	},
	{
		iso_3166_1: "MG",
		english_name: "Madagascar",
		native_name: "Мадагаскар",
		is: false,
	},
	{
		iso_3166_1: "MH",
		english_name: "Marshall Islands",
		native_name: "Маршалови острови",
		is: false,
	},
	{
		iso_3166_1: "MK",
		english_name: "Macedonia",
		native_name: "Македония",
		is: false,
	},
	{
		iso_3166_1: "ML",
		english_name: "Mali",
		native_name: "Мали",
		is: false,
	},
	{
		iso_3166_1: "MM",
		english_name: "Myanmar",
		native_name: "Мианмар (Бирма)",
		is: false,
	},
	{
		iso_3166_1: "MN",
		english_name: "Mongolia",
		native_name: "Монголия",
		is: false,
	},
	{
		iso_3166_1: "MO",
		english_name: "Macao",
		native_name: "Макао, САР на Китай",
		is: false,
	},
	{
		iso_3166_1: "MP",
		english_name: "Northern Mariana Islands",
		native_name: "Северни Мариански острови",
		is: false,
	},
	{
		iso_3166_1: "MQ",
		english_name: "Martinique",
		native_name: "Мартиника",
		is: false,
	},
	{
		iso_3166_1: "MR",
		english_name: "Mauritania",
		native_name: "Мавритания",
		is: false,
	},
	{
		iso_3166_1: "MS",
		english_name: "Montserrat",
		native_name: "Монтсерат",
		is: false,
	},
	{
		iso_3166_1: "MT",
		english_name: "Malta",
		native_name: "Малта",
		is: false,
	},
	{
		iso_3166_1: "MU",
		english_name: "Mauritius",
		native_name: "Мавриций",
		is: false,
	},
	{
		iso_3166_1: "MV",
		english_name: "Maldives",
		native_name: "Малдиви",
		is: false,
	},
	{
		iso_3166_1: "MW",
		english_name: "Malawi",
		native_name: "Малави",
		is: false,
	},
	{
		iso_3166_1: "MX",
		english_name: "Mexico",
		native_name: "Мексико",
		is: false,
	},
	{
		iso_3166_1: "MY",
		english_name: "Malaysia",
		native_name: "Малайзия",
		is: false,
	},
	{
		iso_3166_1: "MZ",
		english_name: "Mozambique",
		native_name: "Мозамбик",
		is: false,
	},
	{
		iso_3166_1: "NA",
		english_name: "Namibia",
		native_name: "Намибия",
		is: false,
	},
	{
		iso_3166_1: "NC",
		english_name: "New Caledonia",
		native_name: "Нова Каледония",
		is: false,
	},
	{
		iso_3166_1: "NE",
		english_name: "Niger",
		native_name: "Нигер",
		is: false,
	},
	{
		iso_3166_1: "NF",
		english_name: "Norfolk Island",
		native_name: "остров Норфолк",
		is: false,
	},
	{
		iso_3166_1: "NG",
		english_name: "Nigeria",
		native_name: "Нигерия",
		is: false,
	},
	{
		iso_3166_1: "NI",
		english_name: "Nicaragua",
		native_name: "Никарагуа",
		is: false,
	},
	{
		iso_3166_1: "NL",
		english_name: "Netherlands",
		native_name: "Нидерландия",
		is: false,
	},
	{
		iso_3166_1: "NO",
		english_name: "Norway",
		native_name: "Норвегия",
		is: false,
	},
	{
		iso_3166_1: "NP",
		english_name: "Nepal",
		native_name: "Непал",
		is: false,
	},
	{
		iso_3166_1: "NR",
		english_name: "Nauru",
		native_name: "Науру",
		is: false,
	},
	{
		iso_3166_1: "NU",
		english_name: "Niue",
		native_name: "Ниуе",
		is: false,
	},
	{
		iso_3166_1: "NZ",
		english_name: "New Zealand",
		native_name: "Нова Зеландия",
		is: false,
	},
	{
		iso_3166_1: "OM",
		english_name: "Oman",
		native_name: "Оман",
		is: false,
	},
	{
		iso_3166_1: "PA",
		english_name: "Panama",
		native_name: "Панама",
		is: false,
	},
	{
		iso_3166_1: "PE",
		english_name: "Peru",
		native_name: "Перу",
		is: false,
	},
	{
		iso_3166_1: "PF",
		english_name: "French Polynesia",
		native_name: "Френска Полинезия",
		is: false,
	},
	{
		iso_3166_1: "PG",
		english_name: "Papua New Guinea",
		native_name: "Папуа Нова Гвинея",
		is: false,
	},
	{
		iso_3166_1: "PH",
		english_name: "Philippines",
		native_name: "Филипини",
		is: false,
	},
	{
		iso_3166_1: "PK",
		english_name: "Pakistan",
		native_name: "Пакистан",
		is: false,
	},
	{
		iso_3166_1: "PL",
		english_name: "Poland",
		native_name: "Полша",
		is: false,
	},
	{
		iso_3166_1: "PM",
		english_name: "St. Pierre and Miquelon",
		native_name: "Сен Пиер и Микелон",
		is: false,
	},
	{
		iso_3166_1: "PN",
		english_name: "Pitcairn Island",
		native_name: "Острови Питкерн",
		is: false,
	},
	{
		iso_3166_1: "PR",
		english_name: "Puerto Rico",
		native_name: "Пуерто Рико",
		is: false,
	},
	{
		iso_3166_1: "PS",
		english_name: "Palestinian Territory",
		native_name: "Палестински територии",
		is: false,
	},
	{
		iso_3166_1: "PT",
		english_name: "Portugal",
		native_name: "Португалия",
		is: false,
	},
	{
		iso_3166_1: "PW",
		english_name: "Palau",
		native_name: "Палау",
		is: false,
	},
	{
		iso_3166_1: "PY",
		english_name: "Paraguay",
		native_name: "Парагвай",
		is: false,
	},
	{
		iso_3166_1: "QA",
		english_name: "Qatar",
		native_name: "Катар",
		is: false,
	},
	{
		iso_3166_1: "RE",
		english_name: "Reunion",
		native_name: "Реюнион",
		is: false,
	},
	{
		iso_3166_1: "RO",
		english_name: "Romania",
		native_name: "Румъния",
		is: false,
	},
	{
		iso_3166_1: "RS",
		english_name: "Serbia",
		native_name: "Сърбия",
		is: false,
	},
	{
		iso_3166_1: "RU",
		english_name: "Russia",
		native_name: "Русия",
		is: false,
	},
	{
		iso_3166_1: "RW",
		english_name: "Rwanda",
		native_name: "Руанда",
		is: false,
	},
	{
		iso_3166_1: "SA",
		english_name: "Saudi Arabia",
		native_name: "Саудитска Арабия",
		is: false,
	},
	{
		iso_3166_1: "SB",
		english_name: "Solomon Islands",
		native_name: "Соломонови острови",
		is: false,
	},
	{
		iso_3166_1: "SC",
		english_name: "Seychelles",
		native_name: "Сейшели",
		is: false,
	},
	{
		iso_3166_1: "SD",
		english_name: "Sudan",
		native_name: "Судан",
		is: false,
	},
	{
		iso_3166_1: "SE",
		english_name: "Sweden",
		native_name: "Швеция",
		is: false,
	},
	{
		iso_3166_1: "SG",
		english_name: "Singapore",
		native_name: "Сингапур",
		is: false,
	},
	{
		iso_3166_1: "SH",
		english_name: "St. Helena",
		native_name: "Света Елена",
		is: false,
	},
	{
		iso_3166_1: "SI",
		english_name: "Slovenia",
		native_name: "Словения",
		is: false,
	},
	{
		iso_3166_1: "SJ",
		english_name: "Svalbard & Jan Mayen Islands",
		native_name: "Свалбард и Ян Майен",
		is: false,
	},
	{
		iso_3166_1: "SK",
		english_name: "Slovakia",
		native_name: "Словакия",
		is: false,
	},
	{
		iso_3166_1: "SL",
		english_name: "Sierra Leone",
		native_name: "Сиера Леоне",
		is: false,
	},
	{
		iso_3166_1: "SM",
		english_name: "San Marino",
		native_name: "Сан Марино",
		is: false,
	},
	{
		iso_3166_1: "SN",
		english_name: "Senegal",
		native_name: "Сенегал",
		is: false,
	},
	{
		iso_3166_1: "SO",
		english_name: "Somalia",
		native_name: "Сомалия",
		is: false,
	},
	{
		iso_3166_1: "SR",
		english_name: "Suriname",
		native_name: "Суринам",
		is: false,
	},
	{
		iso_3166_1: "SS",
		english_name: "South Sudan",
		native_name: "Южен Судан",
		is: false,
	},
	{
		iso_3166_1: "ST",
		english_name: "Sao Tome and Principe",
		native_name: "Сао Томе и Принсипи",
		is: false,
	},
	{
		iso_3166_1: "SU",
		english_name: "Soviet Union",
		native_name: "Soviet Union",
		is: false,
	},
	{
		iso_3166_1: "SV",
		english_name: "El Salvador",
		native_name: "Салвадор",
		is: false,
	},
	{
		iso_3166_1: "SY",
		english_name: "Syrian Arab Republic",
		native_name: "Сирия",
		is: false,
	},
	{
		iso_3166_1: "SZ",
		english_name: "Swaziland",
		native_name: "Свазиленд",
		is: false,
	},
	{
		iso_3166_1: "TC",
		english_name: "Turks and Caicos Islands",
		native_name: "острови Търкс и Кайкос",
		is: false,
	},
	{
		iso_3166_1: "TD",
		english_name: "Chad",
		native_name: "Чад",
		is: false,
	},
	{
		iso_3166_1: "TF",
		english_name: "French Southern Territories",
		native_name: "Френски южни територии",
		is: false,
	},
	{
		iso_3166_1: "TG",
		english_name: "Togo",
		native_name: "Того",
		is: false,
	},
	{
		iso_3166_1: "TH",
		english_name: "Thailand",
		native_name: "Тайланд",
		is: false,
	},
	{
		iso_3166_1: "TJ",
		english_name: "Tajikistan",
		native_name: "Таджикистан",
		is: false,
	},
	{
		iso_3166_1: "TK",
		english_name: "Tokelau",
		native_name: "Токелау",
		is: false,
	},
	{
		iso_3166_1: "TL",
		english_name: "Timor-Leste",
		native_name: "Източен Тимор",
		is: false,
	},
	{
		iso_3166_1: "TM",
		english_name: "Turkmenistan",
		native_name: "Туркменистан",
		is: false,
	},
	{
		iso_3166_1: "TN",
		english_name: "Tunisia",
		native_name: "Тунис",
		is: false,
	},
	{
		iso_3166_1: "TO",
		english_name: "Tonga",
		native_name: "Тонга",
		is: false,
	},
	{
		iso_3166_1: "TP",
		english_name: "East Timor",
		native_name: "East Timor",
		is: false,
	},
	{
		iso_3166_1: "TR",
		english_name: "Turkey",
		native_name: "Турция",
		is: false,
	},
	{
		iso_3166_1: "TT",
		english_name: "Trinidad and Tobago",
		native_name: "Тринидад и Тобаго",
		is: false,
	},
	{
		iso_3166_1: "TV",
		english_name: "Tuvalu",
		native_name: "Тувалу",
		is: false,
	},
	{
		iso_3166_1: "TW",
		english_name: "Taiwan",
		native_name: "Тайван",
		is: false,
	},
	{
		iso_3166_1: "TZ",
		english_name: "Tanzania",
		native_name: "Танзания",
		is: false,
	},
	{
		iso_3166_1: "UA",
		english_name: "Ukraine",
		native_name: "Украйна",
		is: false,
	},
	{
		iso_3166_1: "UG",
		english_name: "Uganda",
		native_name: "Уганда",
		is: false,
	},
	{
		iso_3166_1: "UM",
		english_name: "United States Minor Outlying Islands",
		native_name: "Отдалечени острови на САЩ",
		is: false,
	},
	{
		iso_3166_1: "US",
		english_name: "United States of America",
		native_name: "Съединени щати",
		is: false,
	},
	{
		iso_3166_1: "UY",
		english_name: "Uruguay",
		native_name: "Уругвай",
		is: false,
	},
	{
		iso_3166_1: "UZ",
		english_name: "Uzbekistan",
		native_name: "Узбекистан",
		is: false,
	},
	{
		iso_3166_1: "VA",
		english_name: "Holy See",
		native_name: "Ватикан",
		is: false,
	},
	{
		iso_3166_1: "VC",
		english_name: "St. Vincent and the Grenadines",
		native_name: "Сейнт Винсънт и Гренадини",
		is: false,
	},
	{
		iso_3166_1: "VE",
		english_name: "Venezuela",
		native_name: "Венецуела",
		is: false,
	},
	{
		iso_3166_1: "VG",
		english_name: "British Virgin Islands",
		native_name: "Британски Вирджински острови",
		is: false,
	},
	{
		iso_3166_1: "VI",
		english_name: "US Virgin Islands",
		native_name: "Американски Вирджински острови",
		is: false,
	},
	{
		iso_3166_1: "VN",
		english_name: "Vietnam",
		native_name: "Виетнам",
		is: false,
	},
	{
		iso_3166_1: "VU",
		english_name: "Vanuatu",
		native_name: "Вануату",
		is: false,
	},
	{
		iso_3166_1: "WF",
		english_name: "Wallis and Futuna Islands",
		native_name: "Уолис и Футуна",
		is: false,
	},
	{
		iso_3166_1: "WS",
		english_name: "Samoa",
		native_name: "Самоа",
		is: false,
	},
	{
		iso_3166_1: "XC",
		english_name: "Czechoslovakia",
		native_name: "Czechoslovakia",
		is: false,
	},
	{
		iso_3166_1: "XG",
		english_name: "East Germany",
		native_name: "East Germany",
		is: false,
	},
	{
		iso_3166_1: "XI",
		english_name: "Northern Ireland",
		native_name: "Northern Ireland",
		is: false,
	},
	{
		iso_3166_1: "XK",
		english_name: "Kosovo",
		native_name: "Косово",
		is: false,
	},
	{
		iso_3166_1: "YE",
		english_name: "Yemen",
		native_name: "Йемен",
		is: false,
	},
	{
		iso_3166_1: "YT",
		english_name: "Mayotte",
		native_name: "Майот",
		is: false,
	},
	{
		iso_3166_1: "YU",
		english_name: "Yugoslavia",
		native_name: "Yugoslavia",
		is: false,
	},
	{
		iso_3166_1: "ZA",
		english_name: "South Africa",
		native_name: "Южна Африка",
		is: false,
	},
	{
		iso_3166_1: "ZM",
		english_name: "Zambia",
		native_name: "Замбия",
		is: false,
	},
	{
		iso_3166_1: "ZR",
		english_name: "Zaire",
		native_name: "Zaire",
		is: false,
	},
	{
		iso_3166_1: "ZW",
		english_name: "Zimbabwe",
		native_name: "Зимбабве",
		is: false,
	},
];
